streamdevs/webhook

- .github/workflows/nodejs.yml
Use actions/cache@v1 to cache `node_modules` content and skip `yarn install`
Fixes #7
> Cache dependencies on CI build

- src/config.js
- src/index.js
- src/routes/github/index.js
- src/server.js
- test/routes/github/index.spec.js
Related to #26 
To prevent a merge hell every time we change our routes, this PR moves all the route definitions to a different file.
Since the route is `GET /github`, I move the route definition to the `routes/github/index.js`, maybe if we have more routes for GitHub, we can split each route into their own file.
Also, this PR prevents the logging system to be set up during the tests.
> Move route to a new file

- src/config.js
- src/services/StreamLabs.js
- test/services/StreamLabs.spec.js
Related to #12 
It's time to avoid repeating the same code to send the notifications to StreamLabs, this PR adds a StreamLabs service with a method to send `alerts`.
P.S.: It's only the implementation, we need to merge all PR related with #26 before we can use it 😜
> feat: new StreamLabs service

- package.json
This PR makes Heroku compile the app before running the compiled JS
Related to #50
> Run compiled TypeScript in Heroku

- jest.config.js
- package.json
- yarn.lock
This PR installs `ts-jest` as a dev dependency and add the `ts-jest` preset to the `jest.config.js`.
> test: add 'ts-jest'

- package.json
- src/@types/laabr/index.d.ts
- src/server.ts
- yarn.lock
In order to make the server migration works, we need to do a couple of things:
- Install the proper `hapi` types.
- Define the `laabr` module, it doesn't have TypeScript support.
- Rename `server.js` to `server.ts` and adds missing types.
> refactor: migrate 'server' to TypeScript

- src/services/StreamLabs.ts
This PR fixes the `StreamLabs` constructor because it has all the params as required, but the logger is optional 😅
> fix: 'StreamLabs' types

- src/reactions/github/ping.ts
- test/reactions/github/ping.spec.ts
This PR adds a new 'Ping' reaction class.
> feat: add new 'Ping' reaction

- src/reactions/github/ping.ts
- test/reactions/github/ping.spec.ts
While I was working on this I notice that we weren't catching any errors in the `Ping` reaction, this PR solves that.
Also, now the request to `StreamLabs` and `TwitchChat` run in parallel, instead of sequentially.
> feat: allow Twitch/StreamLabs to fail without breaking other notifications

- src/reactions/github/ping.ts
- src/reactions/github/pull-request-opened.ts
- src/reactions/github/reaction.ts
- src/reactions/github/star.ts
- test/reactions/github/ping.spec.ts
- test/reactions/github/pull-request-opened.spec.ts
- test/reactions/github/star.spec.ts
This PR creates the new `Reaction` abstract class with all the common logic that we found while we create the reactions: `star`, `pull-request-opened` and `ping`.
It also adds to all `Reactions` the new `canHandle` method as we discussed yesterday :D
> refactor: new 'Reaction' abstract class

- src/reactions/github/pull-request-merged.ts
- test/reactions/github/pull-request-merged.spec.ts
- test/reactions/github/pull-request-opened.spec.ts
> feat: new 'PullRequestMerged' 'Reaction'

- src/routes/github/index.ts
> refactor: routes index to TypeScript

- src/reactions/github/fork.ts
- src/reactions/github/index.js
- src/reactions/github/index.ts
- src/routes/github/index.ts
- src/schemas/github/fork-payload.ts
- src/schemas/github/webhook-payload.ts
- test/reactions/github/fork.spec.ts
Related to #50
This PR does a couple of things (I know, I know 🙏🙏🙏)
- Migrates the barrel file `reactions/github/index.js` to TypeScript
- Implements the new Reaction interface for GitHub's `fork` events
- Introduces the partial typings for GitHub's Webhook `fork` event's payloads
> refactor: Migrate fork to TypeScript

- tsconfig.json
This PR disables JS compilation in `tsc`
It also removes a redundant exclude of the config file for `prettier`
> chore: Disable JS compilation 

- src/reactions/github/fork.ts
- src/reactions/github/index.ts
- src/reactions/github/ping.ts
- src/reactions/github/pull-request-merged.ts
- src/reactions/github/pull-request-opened.ts
- src/reactions/github/reaction.ts
- src/reactions/github/star.ts
- src/routes/github/index.ts
- src/schemas/github/ping-payload.ts
- src/schemas/github/pull-request-payload.ts
- src/schemas/github/star-payload.ts
- src/server.ts
- src/services/StreamLabs.ts
- test/reactions/github/fork.spec.ts
- test/reactions/github/ping.spec.ts
- test/reactions/github/pull-request-merged.spec.ts
- test/reactions/github/pull-request-opened.spec.ts
- test/reactions/github/star.spec.ts
- test/routes/github/ping.spec.ts
- test/routes/github/star.spec.ts
> style: remove eslint warnings

- src/reactions/gitlab/merge-request-opened.ts
- src/schemas/gitlab/merge-request-payload.ts
- test/reactions/gitlab/merge-request-opened.spec.ts
Related to #155 
Programed using TCR, if you ask yourself why 12 commits 😜
> feat: new 'MergeRequestOpened' reaction

- package.json
- src/tsconfig.json
- tsconfig.json
Resolves #161 
docs: https://stackoverflow.com/questions/49094427/vscode-intellisense-import-not-working-within-jest-ts-tests
> chore: fix import inside test files

- src/reactions/gitlab/index.ts
- src/routes/gitlab/index.ts
- src/routes/index.ts
- test/routes/gitlab/merge-request-hook.spec.ts
Resolves #152 
Resolves #155 
🙏🏻
> feat: 'MergeRequestOpened' and 'MergeRequestMerged'

- package.json
> fix: Preload dotenv/config so .env variables are loaded

- src/config.ts
Resolves #176 
Our previous implementation doesn't provide us with an empty array when the env var is not set 😱
> fix: allow 'check_run' to work without env var

- README.md
> docs: add GitLab configuration guide
