.github/workflows/nodejs.yml, readme.md
This PR adds a workflow to run our test suite with GitHub Actions.
=> ci: setup GitHub Actions

package.json, yarn.lock
=> Add missing types dependency

src/server.js, test/server.spec.js
=> Support for 'ping' and 'star' events

.eslintrc.js, .github/workflows/nodejs.yml, package.json, prettier.config.js, src/index.js, src/server.js, test/server.spec.js, yarn.lock
=> Setup ESLint and Prettier

package.json, src/index.js, src/server.js, test/server.spec.js, yarn.lock
=> feat: Add laabr logger for hapis and log error events

.env.example, .gitignore, package.json
Simple dotenv implementation with one example in .dotenv.example file.
Please let me know if I neet to change something else.
Related to  #35
=> Dotenv implementation

README.md
=> docs(readme): Clarify environment variables

.github/workflows/nodejs.yml
=> ci: Skip build if commit messages include [skip ci]

package.json, src/services/TwitchChat.js, test/services/TwitchChat.spec.js, yarn.lock
Related to #12 
This PR adds our first service to handle the connections with the Twitch Chat and allows us to send messages.
It is a simple wrapper of the [tmi.js](https://github.com/tmijs/tmi.js) library recommended in the Twitch docs, to handle connection and disconnections to Twitch chat.
=> feat: new TwitchChat service

README.md, app.json, src/config.js
Related with #12 
This PR loads the needed configuration for the TwitchChat service. Also, add the proper documentation to the README.md file about the new configuration tokens.
=> TwitchChat config

src/routes/github/index.js, test/routes/github/index.spec.js
Related to #26 
> Draft until #29 
This PR adds code to handle the `pull_request` `opened` event to send a notification to StreamLabs.
Also, it modifies the `ping` event handle to accept the `pull_request` one.
=> Handle open pull request

src/routes/github/index.js, test/routes/github/index.spec.js
Related to #26 
> Draft until #29 
This PR adds support to send pull request "merged" events to StreamLabs
=> Handle "merged" pull request

src/routes/github/index.js, test/routes/github/index.spec.js
=> refactor: use 'StreamLabs' instead of 'axios'

src/routes/github/index.js, src/schemas/gitHubWebhookPayload.js, test/routes/github/index.spec.js
=> fix: pull request login name

src/routes/github/index.js, test/routes/github/index.spec.js
Related to #12 
This PR adds Twitch Chat notifications to `star` events 🌟
=> feat: send star notifications to twitch chat

src/routes/github/index.js, src/server.js, src/services/StreamLabs.js, test/services/StreamLabs.spec.js
=> feat: Add logs for StreamLabs API errors

.editorconfig, prettier.config.js
This PR adds the `.editorconfig` file so we can ensure consistency across the team.
Resolves #37
=> chore: Add .editorconfig

src/reactions/github/fork.js, src/reactions/github/index.js, src/routes/github/index.js, src/schemas/gitHubWebhookPayload.js, test/routes/github/index.spec.js
=> feat: Send alert to StreamLabs on 'fork' events

src/routes/github/index.js, test/routes/github/index.spec.js
Related to #12 
This PR adds support for pull request events in Twitch Chat.
=> feat: add support for pull request events in Twitch Chat

.gitignore
This PR adds the coverage folder to our `.gitignore`
=> chore: update .gitignore [skip ci]

.gitignore, package.json, tsconfig.json, yarn.lock
=> chore: add TypeScript

src/reactions/github/fork.js
=> fix: Wait for Stream Labs alert to be sent

src/routes/github/index.js, test/routes/github/fork.spec.js, test/routes/github/index.spec.js, test/routes/github/ping.spec.js, test/routes/github/pull_request.spec.js, test/routes/github/star.spec.js
=> feat: add support for ping events in Twitch Chat

src/reactions/github/fork.js, test/routes/github/fork.spec.js
=> fix: Fix args passed to StreamLabs.alert

.github/workflows/nodejs.yml
Related to #50
This PR adds a new compile step to our workflow.
=> ci: add compile step

src/routes/github/index.js, src/schemas/gitHubWebhookPayload.js, test/routes/github/pull_request.spec.js
=> Fix 'pull_request' payload

package.json
=> deploy: change 'postinstall' to 'build'

src/reactions/github/fork.js, src/routes/github/index.js, test/routes/github/fork.spec.js
=> feat: Send message to Twitch Chat on 'fork' events

src/reactions/github/fork.js, src/routes/github/index.js, src/schemas/gitHubWebhookPayload.js, src/services/StreamLabs.js
=> feat: Return response with reaction handling status

tsconfig.json
=> fix: Make tsc ignore files in dist

jest.config.js
=> fix: Make jest ignore files in dist

test/routes/github/fork.spec.ts
=> refactor: migrate 'fork' spec to TypeScript

test/routes/github/index.spec.ts
=> refactor: migrate 'index' spec to TypeScript

test/routes/github/ping.spec.ts
=> refactor: migrate 'ping' spec to TypeScript

test/routes/github/pull_request.spec.ts
=> refactor: migrate 'pull_request' spec to TypeScript

test/routes/github/star.spec.ts
=> refactor: migrate 'star' spec to TypeScript

test/services/StreamLabs.spec.ts
=> refactor: migrate 'StreamLabs' spec to TypeScript

src/config.ts
=> refactor: migrate 'config' to TypeScript

README.md
=> docs: Add contributing section

src/reactions/github/star.ts, test/reactions/github/star.spec.ts
=> feat: new 'Star' reaction

src/reactions/github/pull-request-opened.ts, test/reactions/github/pull-request-opened.spec.ts
This PR adds the new `PullRequestOpened` reaction since makes more sense to me create different reactions for opened and merged pull request.
=> feat: new 'PullRequestOpened' reaction

README.md
=> docs: add GIF to README.md

src/index.js, src/index.ts
=> refactor: migrate 'index.js' to TypeScript

src/reactions/github/index.ts, src/routes/github/index.ts, test/reactions/github/fork.spec.ts, test/routes/github/ping.spec.ts, test/routes/github/pull_request.spec.ts, test/routes/github/star.spec.ts
Resolves #55 
This is my proposal to resolve the #55 issue, any feedback? any change? Feel free to leave it here.
=> refactor: use reactions in 'route'

.eslintrc.js, package.json, src/reactions/github/fork.ts, src/reactions/github/reaction.ts, src/routes/github/index.ts, src/schemas/gitHubWebhookHeaders.ts, src/schemas/gitHubWebhookPayload.ts, src/server.ts, src/services/StreamLabs.ts, src/services/TwitchChat.ts, test/routes/github/fork.spec.ts, test/routes/github/ping.spec.ts, test/routes/github/pull_request.spec.ts, test/routes/github/star.spec.ts, test/services/StreamLabs.spec.ts, yarn.lock
=> Lint TypeScript files with eslint

src/reactions/github/issue-opened.ts, src/schemas/github/issue-payload.ts, test/reactions/github/issue-opened.spec.ts
=> feat: new 'IssueOpened' reaction

husky.config.js, lint-staged.config.js, package.json, yarn.lock
Fixes #120 
We end up using only lint-staged, which runs the two tasks we have for formatting and linting.
=> fix: Formatted / linted files are not added to git

test/__mocks__/StreamLabs.ts, test/__mocks__/TwitchChat.ts, test/reactions/github/fork.spec.ts, test/reactions/github/ping.spec.ts, test/reactions/github/pull-request-merged.spec.ts, test/reactions/github/pull-request-opened.spec.ts, test/reactions/github/star.spec.ts
=> test: new StreamLabs and TwitchChat

prettier.config.js, src/reactions/github/fork.ts, src/reactions/github/issue-opened.ts, src/reactions/github/ping.ts, src/reactions/github/pull-request-merged.ts, src/reactions/github/pull-request-opened.ts, src/reactions/github/reaction.ts, src/reactions/github/star.ts, src/routes/github/index.ts, src/server.ts, test/routes/github/fork.spec.ts, test/services/StreamLabs.spec.ts
=> feat: Added line width to 100 characters

src/reactions/github/index.ts
=> feat: new 'IssueOpened' reaction added to reactionBuild

src/reactions/github/ping.ts, test/reactions/github/ping.spec.ts
=> feat: add 'issues' as available event for 'ping'

src/reactions/github/check-run.ts, src/reactions/github/index.ts, src/reactions/github/ping.ts, src/schemas/github/check-run-payload.ts, src/schemas/webhook-response.ts, test/reactions/github/check-run.spec.ts, test/reactions/github/ping.spec.ts, test/routes/github/check-run.spec.ts
Related to #56 
This PR uses the new format for Twitch Chat messages starting with `/me` for better visibility
=> Implement reaction for check_run events

README.md, app.json, src/config.ts, src/reactions/github/index.ts, src/reactions/github/issue-assigned.ts, src/reactions/github/reaction.ts, src/routes/github/index.ts, src/schemas/github/issue-payload.ts, test/reactions/github/issue-assigned.spec.ts, test/routes/github/issues.spec.ts
Related #58 
This PR implements a new reaction `IssueAssigned`. This reaction allows the user to skip some notifications by using the new env var.
=> feat: new assigned issue reaction

README.md, src/config.ts, src/reactions/github/pull-request-opened.ts, test/reactions/github/pull-request-opened.spec.ts
=> feat: ignore PR opened by some users

src/reactions/github/ping.ts, test/reactions/github/ping.spec.ts
=> feat: support for 'sponsorship' events in 'ping'

README.md, app.json, src/config.ts, src/reactions/github/check-run.ts, src/reactions/github/reaction.ts, test/reactions/github/check-run.spec.ts
=> feature: Opt-int branch-specific notifications

src/reactions/github/check-run.ts, src/reactions/github/fork.ts, src/reactions/github/issue-assigned.ts, src/reactions/github/issue-opened.ts, src/reactions/github/ping.ts, src/reactions/github/pull-request-merged.ts, src/reactions/github/pull-request-opened.ts, src/reactions/github/star.ts, src/services/TwitchChat.ts, test/reactions/github/check-run.spec.ts, test/reactions/github/fork.spec.ts, test/reactions/github/issue-assigned.spec.ts, test/reactions/github/issue-opened.spec.ts, test/reactions/github/ping.spec.ts, test/reactions/github/pull-request-merged.spec.ts, test/reactions/github/pull-request-opened.spec.ts, test/reactions/github/star.spec.ts, test/routes/github/check-run.spec.ts, test/routes/github/fork.spec.ts, test/routes/github/ping.spec.ts, test/routes/github/pull_request.spec.ts, test/routes/github/star.spec.ts, test/services/TwitchChat.spec.ts
=> fix: remove * from Twitch messages

tsconfig.json
=> fix: Do not compile the tests directory

README.md, package.json, src/reactions/github/sponsorshipt-created.ts, src/schemas/github/sponsorship-payload.ts, test/builders/sponsorship-payload-builder.ts, test/reactions/github/sponsorship-created.spec.ts
Related to #67 
This PR adds the new `SponsorshiptCreated` reaction.
=> feat: new `SponsorshipCreated` reaction

package.json
=> fix: start command

src/routes/gitlab/index.ts, src/routes/index.ts, src/schemas/gitlab/joi/gitlab-headers-schema.ts, src/server.ts, test/routes/gitlab/index.spec.ts
=> feat: new `/gitlab` endpoint

src/reactions/gitlab/merge-request-merged.ts, src/schemas/gitlab/merge-request-payload.ts, test/builders/payload/gitlab/merge-request-payload-builder.ts, test/reactions/gitlab/merge-request-merged.spec.ts
=> feat: new 'MergeRequestMerged' reaction

lint-staged.config.js
=> chore: Format markdown files if they have changed in the commit

lint-staged.config.js
=> fix: Update glob expression

changelog.md
=> chore: Create initial release changelog

package.json, src/schemas/github/pull-request-payload.ts, test/builders/github/pull-request-payload-builder.ts, test/reactions/github/pull-request-merged.spec.ts, test/reactions/github/pull-request-opened.spec.ts, test/routes/github/pull_request.spec.ts, yarn.lock
This PR adds the `PullRequestPayloadBuilder` with a new dev dependency [utility-types](https://github.com/piotrwitek/utility-types)
Also, we update the `PullRequestPayload` to add the new `html_url`.
=> test: new 'PullRequestPayloadBuilder'

src/reactions/gitlab/merge-request-merged.ts, src/reactions/gitlab/merge-request-opened.ts, src/schemas/gitlab/merge-request-payload.ts, test/builders/gitlab/merge-request-payload-builder.ts, test/reactions/gitlab/merge-request-merged.spec.ts, test/reactions/gitlab/merge-request-opened.spec.ts
=> feat: send mr link in mr events

src/reactions/github/pull-request-opened.ts, test/reactions/github/pull-request-opened.spec.ts
=> feat: send pull request link in opened pull requests

src/reactions/github/pull-request-merged.ts, test/reactions/github/pull-request-merged.spec.ts
=> feat: send pull request link in merged pull requests

src/reactions/github/issue-assigned.ts, src/reactions/github/issue-opened.ts, src/schemas/github/issue-payload.ts, test/builders/github/issue-payload-builder.ts, test/reactions/github/issue-assigned.spec.ts, test/reactions/github/issue-opened.spec.ts, test/routes/github/issues.spec.ts
=> feat: send issue url to Twitch Chat
